- Media Hub:
    - Plex Subgroup:
      - Plex:
          icon: plex
          href: {{HOMEPAGE_VAR_PLEX_URL}}
          siteMonitor: {{HOMEPAGE_VAR_PLEX_URL}}
          widget:
            type: plex
            url: {{HOMEPAGE_VAR_PLEX_URL}}
            key: {{HOMEPAGE_VAR_PLEX_KEY}}
            fields: [ "albums", "movies", "tv" ]
      - Statistics for Plex:
          icon: tautulli
          href: {{HOMEPAGE_VAR_TAUTULLI_URL}}
          siteMonitor: {{HOMEPAGE_VAR_TAUTULLI_RAW_URL}}
          widget:
            type: tautulli
            url: {{HOMEPAGE_VAR_TAUTULLI_RAW_URL}}
            key: {{HOMEPAGE_VAR_TAUTULLI_KEY}}
            enableUser: true
            showEpisodeNumber: true
            expandOneStreamToTwoRows: true
    - Synology:
      - Disk Station:
          icon: synology-dsm
          href: {{HOMEPAGE_VAR_DISKSTATION_URL}}
          siteMonitor: {{HOMEPAGE_VAR_DISKSTATION_URL}}
          widget:
            type: diskstation
            url: {{HOMEPAGE_VAR_DISKSTATION_URL}}
            username: {{HOMEPAGE_VAR_DISKSTATION_USER}}
            password: {{HOMEPAGE_VAR_DISKSTATION_PASSWORD}}
      - Download Station:
          icon: synology-download-station
          href: {{HOMEPAGE_VAR_DISKSTATION_URL}}
          siteMonitor: {{HOMEPAGE_VAR_DISKSTATION_URL}}
          widget:
            type: downloadstation
            url: {{HOMEPAGE_VAR_DISKSTATION_URL}}
            username: {{HOMEPAGE_VAR_DISKSTATION_USER}}
            password: {{HOMEPAGE_VAR_DISKSTATION_PASSWORD}}
    - Torrents:
      - qBittorrent:
          icon: qbittorrent
          href: {{HOMEPAGE_VAR_TORRENTS_URL}}
          siteMonitor: {{HOMEPAGE_VAR_TORRENTS_URL}}
          widget:
            type: qbittorrent
            url: {{HOMEPAGE_VAR_TORRENTS_URL}}
            username: {{HOMEPAGE_VAR_TORRENTS_USER}}
            password: {{HOMEPAGE_VAR_TORRENTS_PASS}}
      - Torrents UI:
          icon: flood
          href: {{HOMEPAGE_VAR_TORRENTS_UI_URL}}
          siteMonitor: {{HOMEPAGE_VAR_TORRENTS_UI_URL}}
          widget:
            type: flood
            url: {{HOMEPAGE_VAR_TORRENTS_UI_URL}}
            username: {{HOMEPAGE_VAR_TORRENTS_UI_USER}}
            password: {{HOMEPAGE_VAR_TORRENTS_UI_PASS}}
- Smart Home:
    - Home Assistant:
        icon: home-assistant
        href: {{HOMEPAGE_VAR_HOMEASSISTANT_URL}}
        siteMonitor: {{HOMEPAGE_VAR_HOMEASSISTANT_URL}}
        widget:
          type: homeassistant
          url: {{HOMEPAGE_VAR_HOMEASSISTANT_URL}}
          key: {{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}

- Network & Storage:
    - Unifi Controller:
        icon: unifi
        href: https://unifi.ui.com
        siteMonitor: https://192.168.198.1
        widget:
          type: unifi
          url: https://192.168.198.1
          key: {{HOMEPAGE_VAR_UNIFI_CONTROLLER_KEY}}
          fields: ["uptime", "wan", "lan_users", "wlan_users"]
    - Network:
      - Traefik:
          icon: traefik
          href: {{HOMEPAGE_VAR_TRAEFIK_URL}}
          siteMonitor: {{HOMEPAGE_VAR_TRAEFIK_URL}}
          widget:
            type: traefik
            url: {{HOMEPAGE_VAR_TRAEFIK_URL}}
      - Pi Hole:
          icon: pi-hole
          href: "{{HOMEPAGE_VAR_PI_HOLE_URL}}/admin"
          siteMonitor: {{HOMEPAGE_VAR_PI_HOLE_URL}}
          widget:
            type: pihole
            version: 6
            url: {{HOMEPAGE_VAR_PI_HOLE_URL}}
            key: {{HOMEPAGE_VAR_PI_HOLE_KEY}}
    - DNS:
      - Gitea:
          icon: gitea
          href: {{HOMEPAGE_VAR_GITEA_URL}}
          siteMonitor: {{HOMEPAGE_VAR_GITEA_URL}}
          widget:
            type: gitea
            fields: ["repositories", "issues", "pulls"]
            url: {{HOMEPAGE_VAR_GITEA_URL}}
            key: {{HOMEPAGE_VAR_GITEA_KEY}}
- Observability & Health:
     - Health Check:
        icon: uptime-kuma
        href: {{HOMEPAGE_VAR_HEALTH_CHECK_URL}}
        siteMonitor: {{HOMEPAGE_VAR_HEALTH_CHECK_URL}}
        widget:
          type: uptimekuma
          url: {{HOMEPAGE_VAR_HEALTH_CHECK_URL}}
          slug: {{HOMEPAGE_VAR_HEALTH_CHECK_SLUG}}

     - Grafana:
        icon: grafana
        href: {{HOMEPAGE_VAR_GRAFANA_URL}}
        siteMonitor: {{HOMEPAGE_VAR_GRAFANA_URL}}
        widget:
          type: grafana
          fields: ["dashboards", "datasources"]
          url: {{HOMEPAGE_VAR_GRAFANA_URL}}
          username: {{HOMEPAGE_VAR_GRAFANA_USER}}
          password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
     - Prometheus:
        icon: prometheus
        href: {{HOMEPAGE_VAR_PROMETHEUS_URL}}
        siteMonitor: {{HOMEPAGE_VAR_PROMETHEUS_URL}}
        widget:
          type: prometheus
          url: {{HOMEPAGE_VAR_PROMETHEUS_URL}}
- Bookmarks:
    - Influx:
        id: simple_icon
        icon: influxdb
        href: {{HOMEPAGE_VAR_INFLUX_URL}}
    - Local Docker Logs:
        id: simple_icon
        icon: dozzle
        href: {{HOMEPAGE_VAR_LOCAL_DOCKER_LOGS_URL}}
    - Phoenix:
        id: simple_icon
        icon: si-apache
        href: {{HOMEPAGE_VAR_PHOENIX_URL}}
    - Twitch:
        id: simple_icon
        icon: twitch
        href: {{HOMEPAGE_VAR_TWITCH_URL}}
    - Sonos:
        id: simple_icon
        icon: solidtime-light
        href: https://play.sonos.com/en-us/web-app
    - Torrents Search:
        id: simple_icon
        icon: webtorrent
        href: https://search.extto.com/
    - LLM Tools:
        id: simple_icon
        icon: claude-ai
        href: https://shir-man.com/
    - Omni Turtle Search:
        id: simple_icon
        icon: https://omni-search.pkarpovich.space/icon.png
        href: https://omni-search.pkarpovich.space
    - Magnet Feed Sync:
        id: simple_icon
        icon: https://magnet-feed-sync.pkarpovich.space/logo.png
        href: https://magnet-feed-sync.pkarpovich.space/?debug=true
    - Content Oracle:
        id: simple_icon
        icon: https://content-oracle.pkarpovich.space/favicon.ico
        href: https://content-oracle.pkarpovich.space
- Weather:
    - Windy:
        id: simple_widget
        widget:
          type: iframe
          name: myIframe
          allowFullscreen: false
          src: {{HOMEPAGE_VAR_WINDY_EMBED_WIDGET_URL}}
